# Generated by Django 3.2.7 on 2021-09-10 11:23

import json
from pathlib import Path

from todo_app.settings import STATIC_ROOT, BASE_DIR, CITY_JSON_DATA
from django.db import migrations


def insert_data(apps, schema_editor):
    City = apps.get_model("location", "City")
    Country = apps.get_model("location", "Country")

    with open(Path(BASE_DIR, CITY_JSON_DATA), encoding='utf-8') as data_file:
        json_data = json.loads(data_file.read())

        for city_data in json_data:
            country = Country.objects.filter(name=city_data['country'])

            if not country:
                country = Country(name=city_data['country'])
                country.save()
            else:
                country = country[0]

            city_data['country'] = country
            city_data['city_id'] = city_data['id']

            city = City(**city_data)
            city.save()


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_data),
    ]
